parameters:
#    cotacao.example.class: Tex\Bundle\CotacaoBundle\Example

services:
#    cotacao.example:
#        class: %cotacao.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
