<?php

namespace Tex\Bundle\CotacaoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CondutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondutorRepository extends EntityRepository
{
}
